spring.application.name=03-Spring-JDBC-PostgreSQL

#Data Source Properties
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sb01db
spring.datasource.username=root
spring.datasource.password=root@123